# Generated by Django 4.0.5 on 2022-08-09 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('min_processing_time', models.PositiveIntegerField(default=1)),
                ('max_processing_time', models.PositiveIntegerField(default=2)),
                ('starting_from', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('processing_time', models.CharField(max_length=30)),
                ('stay_period', models.IntegerField(default=0)),
                ('validity', models.IntegerField(default=0)),
                ('entry', models.CharField(choices=[('Single', 'Single'), ('Dual', 'Dual'), ('Multiple', 'Multiple')], max_length=20)),
                ('fees', models.IntegerField(default=0)),
                ('photo', models.ImageField(default='photos/default.jpg', upload_to='photos')),
                ('show_on_home', models.BooleanField(default=False)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.country')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=20)),
                ('applicant_phone', models.CharField(max_length=12)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('no_of_persons', models.IntegerField(default=1)),
                ('customer_visa_country', models.CharField(max_length=40)),
                ('customer_visa_type', models.CharField(max_length=40)),
                ('customer_id', models.IntegerField(default=100002022)),
                ('prev_id', models.IntegerField(default=20220000)),
                ('applicant_nationality', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Nil', max_length=10)),
                ('relation_to_applicant', models.CharField(blank=True, default='Self', max_length=50, null=True)),
                ('visa_country', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('passport1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('passport2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('onward_ticket', models.FileField(blank=True, null=True, upload_to='files')),
                ('return_ticket', models.FileField(blank=True, null=True, upload_to='files')),
                ('document1', models.FileField(blank=True, null=True, upload_to='files')),
                ('document2', models.FileField(blank=True, null=True, upload_to='files')),
                ('document3', models.FileField(blank=True, null=True, upload_to='files')),
                ('document4', models.FileField(blank=True, null=True, upload_to='files')),
                ('application_id', models.IntegerField(default=20220000)),
                ('status', models.CharField(choices=[('Documents Uploaded', 'Documents Uploaded'), ('Sent for visa processing', 'Sent for visa processing'), ('Visa approved', 'Visa approved'), ('Application rejected', 'Application rejected')], default='Applied', max_length=50)),
                ('add_person', models.BooleanField(default=False)),
                ('upload_visa', models.FileField(blank=True, null=True, upload_to='visas')),
                ('upload_branch', models.CharField(default='None', max_length=30)),
                ('upload_by', models.CharField(default='None', max_length=30)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('nationality', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=20)),
                ('applicant_phone', models.CharField(max_length=12)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('visa_country', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('application_id', models.IntegerField(default=20220000)),
                ('application_status', models.CharField(choices=[('Applied', 'Applied'), ('Contacted', 'Contacted'), ('Visa applicants added', 'Visa applicants added'), ('Sent for visa processing', 'Sent for visa processing'), ('Visa approved', 'Visa approved')], default='Applied', max_length=50)),
                ('no_of_persons', models.IntegerField(default=1)),
                ('existing_customer', models.BooleanField(default=False)),
                ('prev_id', models.IntegerField(default=20220000)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant_nationality', models.ForeignKey(default='Nil', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.nation')),
            ],
        ),
    ]
