# Generated by Django 4.0.5 on 2022-07-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcustomer',
            name='customer_visa_country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='savedcustomer',
            name='customer_visa_type',
            field=models.CharField(max_length=40),
        ),
    ]
