# Generated by Django 4.0.5 on 2022-07-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_savedcustomer_customer_visa_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedcustomer',
            old_name='customer_name',
            new_name='applicant_name',
        ),
        migrations.AlterField(
            model_name='savedcustomer',
            name='no_of_persons',
            field=models.IntegerField(default=0),
        ),
    ]
