# Generated by Django 4.0.5 on 2022-07-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_customer_name_savedcustomer_applicant_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedcustomer',
            old_name='customer_email',
            new_name='applicant_email',
        ),
        migrations.RenameField(
            model_name='savedcustomer',
            old_name='customer_nationality',
            new_name='applicant_nationality',
        ),
        migrations.RenameField(
            model_name='savedcustomer',
            old_name='customer_phone',
            new_name='applicant_phone',
        ),
    ]
