# Generated by Django 4.0.5 on 2022-07-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_customer_email_savedcustomer_applicant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='no_of_persons',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='savedcustomer',
            name='no_of_persons',
            field=models.IntegerField(default=1),
        ),
    ]
