# Generated by Django 4.0.5 on 2022-07-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_application_save_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='existing_customer',
            field=models.BooleanField(default=False),
        ),
    ]
