# Generated by Django 4.0.5 on 2022-07-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_application_existing_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='prev_id',
            field=models.IntegerField(default=20220000),
        ),
    ]
