# Generated by Django 4.0.5 on 2022-07-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_application_prev_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcustomer',
            name='prev_id',
            field=models.IntegerField(default=20220000),
        ),
    ]
