# Generated by Django 4.0.5 on 2022-07-31 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_savedcustomer_prev_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
