# Generated by Django 4.0.5 on 2022-08-03 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_application_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='process_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='rejected_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
