# Generated by Django 4.0.5 on 2022-08-23 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
                ('activity', models.CharField(max_length=30)),
                ('visa_app_id', models.IntegerField()),
                ('visa_applicant', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
