# Generated by Django 4.0.5 on 2022-07-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neededdocument',
            name='add_more',
            field=models.BooleanField(default=False),
        ),
    ]
